# Generated by Django 4.2.6 on 2023-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_images',
            field=models.ImageField(blank=True, default='usericon.png', null=True, upload_to='profile_images', verbose_name='Profile Picture'),
        ),
    ]
