# Generated by Django 4.2.6 on 2023-11-11 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_rename_profile_img_profile_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_images',
            new_name='profile_images',
        ),
    ]
